fix: can't parse<u>Boolean Operation</u>
code:
bool_ops_text = MarkupText("<u>Boolean Operation</u>").next_to(ellipse1, UP * 3)

error: 
ManimGL v1.6.1
<u>
</u>
Traceback (most recent call last):
  File "d:\anaconda3\envs\manim\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "g:\github\manim\manimlib\__main__.py", line 25, in main
    scene.run()
  File "g:\github\manim\manimlib\scene\scene.py", line 120, in run
    self.construct()
  File "G:\github\manim\sin.py", line 173, in construct
    bool_ops_text = MarkupText("<u>Boolean Operation</u>").next_to(ellipse1, UP * 3)
  File "g:\github\manim\manimlib\mobject\svg\text_mobject.py", line 123, in __init__
    super().__init__(text, **kwargs)
  File "g:\github\manim\manimlib\mobject\svg\string_mobject.py", line 77, in __init__
    self.parse()
  File "g:\github\manim\manimlib\mobject\svg\string_mobject.py", line 262, in parse
    self.get_cmd_span_pairs(cmd_spans, flags)
  File "g:\github\manim\manimlib\mobject\svg\string_mobject.py", line 313, in get_cmd_span_pairs
    raise ValueError("Missing open command")
ValueError: Missing open command